services:
  consul:
    image: docker.io/hashicorp/consul:latest
    container_name: consul
    ports:
      - "18500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
