services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: unless-stopped
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"consul-node1","node_name":"consul-node1"}
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8300:8300"
    networks:
      - consul
    volumes:
      - consul:/consul/data
    command:
      [
        "agent",
        "-server",
        "-ui",
        "-node=consul-node1",
        "-bootstrap-expect=1",
        "-client=0.0.0.0",
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  consul:
    driver: bridge

volumes:
  consul:
