services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = true
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        gitlab_rails['db_host'] = 'gitlab-postgres'
    ports:
      - "36701:80"
      - "36702:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    depends_on:
      - gitlab_postgres
      - gitlab_runner
    networks:
      - gitlab

gitlab-runner:
  image: docker.io/gitlab/gitlab-runner:latest
  container_name: gitlab-runner
  restart: always
  environment:
    RUNNER_NAME: "docker-gitlab-runner"
  networks:
    - gitlab_network
  volumes:
    - gitlab_runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
  user: "root"
  privileged: true

  gitlab-postgres:
    image: docker.io/postgres:alpine
    container_name: gitlab-postgres
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlab
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - gitlab_postgresql:/var/lib/postgresql/data/pgdata
    networks:
      - gitlab

networks:
  gitlab:

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_postgresql:
  gitlab_runner:
# sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
# sudo docker exec -it gitlab bash -c "gitlab-rake "gitlab:password:reset[root]""
# sudo docker exec -it gitlab-runner gitlab-runner register
