services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:36701'
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_username'] = '${POSTGRES_USER:-gitlab}'
        gitlab_rails['db_password'] = '${POSTGRES_PASSWORD:-gitlab}'
        gitlab_rails['db_host'] = 'gitlab-postgres'
    ports:
      - "36701:80"
      - "36702:22"
    volumes:
      - gitlab:/etc/gitlab
      - gitlab:/var/log/gitlab
      - gitlab:/var/opt/gitlab
    depends_on:
      gitlab-postgres:
        condition: service_healthy
    networks:
      - gitlab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 60s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    environment:
      - RUNNER_NAME=docker-gitlab-runner
    volumes:
      - gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  gitlab-postgres:
    image: postgres:16.4-alpine
    container_name: gitlab-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gitlab}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gitlab}
      - POSTGRES_DB=gitlab
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gitlab-postgres:/var/lib/postgresql/data/pgdata
    networks:
      - gitlab
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gitlab"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  gitlab:
    driver: bridge

volumes:
  gitlab:
  gitlab-runner:
  gitlab-postgres:
# sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password
# sudo docker exec -it gitlab bash -c "gitlab-rake "gitlab:password:reset[root]""
# sudo docker exec -it gitlab-runner gitlab-runner register
# sudo docker exec -it gitlab-runner gitlab-runner register
