services:
  jenkins:
    image: docker.io/jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - "18080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  jenkins_network:
