services:
  mongo:
    image: docker.io/mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 17017:27017
    volumes:
      - mongo:/data/db
    networks:
      - mongo
networks:
  mongo:

volumes:
  mongo:
