services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@123Password
    ports:
      - 11433:1433
    networks:
      - mssql
    volumes:
      - mssql:/var/opt/mssql

networks:
  mssql:

volumes:
  mssql:
