services:
  mysql:
    image: mysql:8.0-oraclelinux8
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-215DaDnq7TuFKe}
    ports:
      - "3306:3306"
    networks:
      - mysql
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD:-o90h5ErAIeozNC}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
