services:
  mysql:
    image: docker.io/mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 13306:3306
    networks:
      - mysql_network

networks:
  mysql_network:
