services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="@Nb6&^61*vI50T"
    ports:
      - 13306:3306
    networks:
      - mysql
    volumes:
      - mysql:/var/lib/mysql

networks:
  mysql:

volumes:
  mysql:
