services:
  mysql:
    image: docker.io/mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
