version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "11180:80"  # Expose HTTP port
      - "11443:443"  # Expose HTTPS port (optional)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ./certs:/etc/nginx/certs  # SSL certificates (optional)
    networks:
      - appnet
    depends_on:
      - api1
      - api2

