services:
  postgres:
    image: docker.io/library/postgres:14.15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD="@Nb6&^61*vI50T"
      - POSTGRES_USER=postgres
    ports:
      - 15432:5432
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  postgres:

volumes:
  postgres:
