services:
  postgres:
    image: docker.io/postgres:15.0
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 15432:5432
    networks:
      - postgres_network

networks:
  postgres_network:
