services:
  rabbitmq:
    image: docker.io/rabbitmq:management-alpine
    container_name: rabbitmq
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  rabbitmq_data:
    driver: local
