services:
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-rabbit}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-U4W72RW7Vs0Pxb}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit vm_memory_high_watermark 0.7
    ports:
      - "15672:15672"
      - "15692:15692"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  rabbitmq:
    driver: bridge

volumes:
  rabbitmq:
