services:
  rabbitmq:
    image: docker.io/rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq:
