services:
  rabbitmq:
    image: docker.io/rabbitmq:management-alpine
    restart: always
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    network:
      - rabbitmq_network

networks:
  rabbitmq_network:
