services:
  redis:
    image: docker.io/redis:latest
    container_name: redis
    restart: always
    ports:
      - 16379:6379
    networks:
      - redis
    volumes:
      - redis:/data

networks:
  redis:

volumes:
  redis:

