services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    restart: unless-stopped
    environment:
      - SCYLLA_CLUSTER_NAME=${SCYLLA_CLUSTER_NAME:-scylla}
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_BROADCAST_ADDRESS=127.0.0.1
      - SCYLLA_SEEDS=scylla
    ports:
      - "9042:9042"
      - "9160:9160"
      - "10000:10000"
    networks:
      - scylla
    volumes:
      - scylla:/var/lib/scylla
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2"
        reservations:
          memory: 2G
          cpus: "1"
    command: ["--smp", "2", "--memory", "2G"]

networks:
  scylla:
    driver: bridge

volumes:
  scylla:
