services:
  sonarqube:
    image: docker.io/library/sonarqube:lts-community
    container_name: sonarqube
    restart: always
    depends_on:
      - sonarqube_postgres
    environment:
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_postgres:5432/sonarqube
    ports:
      - "19001:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube

  sonarqube_postgres:
    image: docker.io/library/postgres:16.4-alpine
    container_name: sonarqube_postgres
    restart: always
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_postgres:/var/lib/postgresql/data
    networks:
      - sonarqube

networks:
  sonarqube:

volumes:
  sonarqube_postgres:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
