services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_SERVER_MODE=true
    ports:
      - "8200:8200"
    volumes:
      - vault:/vault/file
    networks:
      - vault
    command: server -dev
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

volumes:
  vault:

networks:
  vault:
