global:
  resolve_timeout: 5m

route:
  receiver: "default-receiver"

receivers:
  - name: "default-receiver"
    email_configs:
      - to: "admin@yourdomain.com"
        from: "alertmanager@yourdomain.com"
        smarthost: "smtp.yourdomain.com:587"
        auth_username: "your-email@yourdomain.com"
        auth_password: "your-email-password"
        require_tls: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
